// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./log.css";

export const puAnsiBlue = "pu-ansi-blue";
export const puAnsiBold = "pu-ansi-bold";
export const puAnsiGreen = "pu-ansi-green";
export const puAnsiRed = "pu-ansi-red";
export const puAnsiYellow = "pu-ansi-yellow";
export const puLog = "pu-log";
export const puLogFooter = "pu-log-footer";
export const puLogLine = "pu-log-line";
export const puLogLineDebug = "pu-log-line--debug";
export const puLogLineError = "pu-log-line--error";
export const puLogLineInfo = "pu-log-line--info";
export const puLogLineWarn = "pu-log-line--warn";
export const puLogLines = "pu-log-lines";
