// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./chat.css";

export const puAssistant = "pu-assistant";
export const puAttach = "pu-attach";
export const puAttachX = "pu-attach-x";
export const puAttachment = "pu-attachment";
export const puChat = "pu-chat";
export const puComposer = "pu-composer";
export const puMic = "pu-mic";
export const puMsg = "pu-msg";
export const puMsgImage = "pu-msg-image";
export const puMsgMd = "pu-msg-md";
export const puUser = "pu-user";
export { puInput } from "../_primitives/controls.css.js";
export { puMd } from "../output/markdown.css.js";
export const puRec = "pu-rec";
