// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./webcam.css";

export const puWebcam = "pu-webcam";
export const puWebcamMirror = "pu-webcam-mirror";
export const puWebcamOffscreen = "pu-webcam-offscreen";
export const puWebcamPlaceholder = "pu-webcam-placeholder";
export const puWebcamStage = "pu-webcam-stage";
export const puWebcamVideo = "pu-webcam-video";
