// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./menu.css";

export const puMenu = "pu-menu";
export const puMenuIcon = "pu-menu-icon";
export const puMenuItem = "pu-menu-item";
export const puMenuItemDanger = "pu-menu-item-danger";
export const puMenuLabel = "pu-menu-label";
export const puMenuSep = "pu-menu-sep";
