// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./label.css";

export const puLabel = "pu-label";
export const puLabelBar = "pu-label-bar";
export const puLabelEmpty = "pu-label-empty";
export const puLabelName = "pu-label-name";
export const puLabelRow = "pu-label-row";
export const puLabelScore = "pu-label-score";
export const puLabelTop = "pu-label-top";
