// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./upload.css";

export const puUpload = "pu-upload";
export const puUploadDrop = "pu-upload-drop";
export const puUploadGlyph = "pu-upload-glyph";
export const puUploadItem = "pu-upload-item";
export const puUploadList = "pu-upload-list";
export const puUploadName = "pu-upload-name";
export const puUploadRemove = "pu-upload-remove";
export const puUploadSize = "pu-upload-size";
export const puUploadThumb = "pu-upload-thumb";
