// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./tabs.css";

export const puTab = "pu-tab";
export const puTabActive = "pu-tab-active";
export const puTabBadge = "pu-tab-badge";
export const puTabClose = "pu-tab-close";
export const puTabLabel = "pu-tab-label";
export const puTabs = "pu-tabs";
export const puTabsBar = "pu-tabs-bar";
export const puTabsPanel = "pu-tabs-panel";
export const puFillY = "pu-fill-y";
