// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./split-pane.css";

export const puSplitPane = "pu-split-pane";
export const puSplitPaneHorizontal = "pu-split-pane--horizontal";
export const puSplitPaneVertical = "pu-split-pane--vertical";
export const puSplitPaneHandle = "pu-split-pane-handle";
export const puSplitPanePanel = "pu-split-pane-panel";
export const puFillY = "pu-fill-y";
