// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./drawer.css";

export const puDrawer = "pu-drawer";
export const puDrawerBody = "pu-drawer-body";
export const puDrawerCollapsed = "pu-drawer-collapsed";
export const puDrawerMain = "pu-drawer-main";
export const puDrawerNav = "pu-drawer-nav";
export const puDrawerToggle = "pu-drawer-toggle";
export const puFillY = "pu-fill-y";
