// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./breadcrumb.css";

export const puBreadcrumb = "pu-breadcrumb";
export const puBreadcrumbCurrent = "pu-breadcrumb-current";
export const puBreadcrumbItem = "pu-breadcrumb-item";
export const puBreadcrumbLink = "pu-breadcrumb-link";
export const puBreadcrumbSep = "pu-breadcrumb-sep";
