// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./toolbar.css";

export const puToolbar = "pu-toolbar";
export const puToolbarBtn = "pu-toolbar-btn";
export const puToolbarBtnDanger = "pu-toolbar-btn--danger";
export const puToolbarBtnPrimary = "pu-toolbar-btn--primary";
export const puToolbarIcon = "pu-toolbar-icon";
export const puToolbarSep = "pu-toolbar-sep";
