// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./annotated-image.css";

export const puAnnimg = "pu-annimg";
export const puAnnimgBase = "pu-annimg-base";
export const puAnnimgBox = "pu-annimg-box";
export const puAnnimgChip = "pu-annimg-chip";
export const puAnnimgEmpty = "pu-annimg-empty";
export const puAnnimgFrame = "pu-annimg-frame";
export const puAnnimgLegend = "pu-annimg-legend";
export const puAnnimgMask = "pu-annimg-mask";
export const puAnnimgSwatch = "pu-annimg-swatch";
export const puAnnimgTag = "pu-annimg-tag";
