// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./highlighted-text.css";

export const puHltext = "pu-hltext";
export const puHltextEmpty = "pu-hltext-empty";
export const puHltextLabel = "pu-hltext-label";
export const puHltextSpan = "pu-hltext-span";
