// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./progress.css";

export const puProgress = "pu-progress";
export const puProgressFill = "pu-progress-fill";
export const puProgressLabel = "pu-progress-label";
export const puProgressTrack = "pu-progress-track";
