// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./file.css";

export const puFile = "pu-file";
export const puFileEmpty = "pu-file-empty";
export const puFileIcon = "pu-file-icon";
export const puFileName = "pu-file-name";
