// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./toast.css";

export const puToast = "pu-toast";
export const puToastError = "pu-toast--error";
export const puToastInfo = "pu-toast--info";
export const puToastSuccess = "pu-toast--success";
export const puToastWarning = "pu-toast--warning";
export const puToastClose = "pu-toast-close";
export const puToastContainer = "pu-toast-container";
export const puToastText = "pu-toast-text";
