// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./tree.css";

export const puTree = "pu-tree";
export const puTreeChildren = "pu-tree-children";
export const puTreeIcon = "pu-tree-icon";
export const puTreeInput = "pu-tree-input";
export const puTreeLabel = "pu-tree-label";
export const puTreeNode = "pu-tree-node";
export const puTreeNodeSelected = "pu-tree-node--selected";
export const puTreeToggle = "pu-tree-toggle";
export const puTreeToggleLeaf = "pu-tree-toggle--leaf";
export const puFillY = "pu-fill-y";
