// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./gallery.css";

export const puGallery = "pu-gallery";
export const puGalleryCell = "pu-gallery-cell";
export const puGalleryEmpty = "pu-gallery-empty";
