// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./sidebar.css";

export const puSidebar = "pu-sidebar";
export const puSidebarCollapsed = "pu-sidebar--collapsed";
export const puSidebarBadge = "pu-sidebar-badge";
export const puSidebarBadgeDanger = "pu-sidebar-badge--danger";
export const puSidebarBadgeInfo = "pu-sidebar-badge--info";
export const puSidebarBadgeSuccess = "pu-sidebar-badge--success";
export const puSidebarBadgeWarning = "pu-sidebar-badge--warning";
export const puSidebarIcon = "pu-sidebar-icon";
export const puSidebarItem = "pu-sidebar-item";
export const puSidebarItemSelected = "pu-sidebar-item--selected";
export const puSidebarLabel = "pu-sidebar-label";
export const puSidebarSection = "pu-sidebar-section";
export const puSidebarSectionLabel = "pu-sidebar-section-label";
export const puSidebarToggle = "pu-sidebar-toggle";
