// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./status-badge.css";

export const puStatusBadge = "pu-status-badge";
export const puStatusBadgeDot = "pu-status-badge-dot";
export const puStatusBadgeLabel = "pu-status-badge-label";
export const puStatusBadgeCompleted = "pu-status-badge--completed";
export const puStatusBadgeError = "pu-status-badge--error";
export const puStatusBadgeFailed = "pu-status-badge--failed";
export const puStatusBadgeIdle = "pu-status-badge--idle";
export const puStatusBadgeRunning = "pu-status-badge--running";
export const puStatusBadgeWaiting = "pu-status-badge--waiting";
