// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./accordion.css";

export const puAccordion = "pu-accordion";
export const puAccordionBody = "pu-accordion-body";
export const puAccordionCaret = "pu-accordion-caret";
export const puAccordionHead = "pu-accordion-head";
export const puAccordionOpen = "pu-accordion-open";
