// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./overlay.css";

export const puNote = "pu-note";
export const puNoteBody = "pu-note-body";
export const puNoteDrop = "pu-note-drop";
export const puNoteError = "pu-note-error";
export const puNoteStack = "pu-note-stack";
export const puNoteWarn = "pu-note-warn";
export const puNoteX = "pu-note-x";
export const puNotes = "pu-notes";
export const puViewError = "pu-view-error";
