// Generated by scripts/gen-css-classes.mjs — do not edit.
import "./styles.css";

export const puBusy = "pu-busy";
export const puBusyBar = "pu-busy-bar";
export const puDesc = "pu-desc";
export const puDisabled = "pu-disabled";
export const puField = "pu-field";
export const puLayout = "pu-layout";
export const puLayoutCol = "pu-layout-col";
export const puLayoutGrid = "pu-layout-grid";
export const puLayoutRow = "pu-layout-row";
export const puPage = "pu-page";
export const puFieldGrow = "pu-field-grow";
export const puFillX = "pu-fill-x";
export const puFillY = "pu-fill-y";
export const puSlot = "pu-slot";
