import "./styles.css";
export declare const puBusy = "pu-busy";
export declare const puBusyBar = "pu-busy-bar";
export declare const puDesc = "pu-desc";
export declare const puDisabled = "pu-disabled";
export declare const puField = "pu-field";
export declare const puLayout = "pu-layout";
export declare const puLayoutCol = "pu-layout-col";
export declare const puLayoutGrid = "pu-layout-grid";
export declare const puLayoutRow = "pu-layout-row";
export declare const puPage = "pu-page";
export declare const puFieldGrow = "pu-field-grow";
